stages:
  - build

pages:
  stage: build
  script:
    - "mkdir public; ls --ignore=public | xargs -I {} mv {} public"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
